version: 1
jobs:
  build:
    docker:
      - image: circleci/php:7.4

    steps:
      - checkout

      - run: sudo composer self-update

      - restore_cache:
          keys:
            - composer-{{ checksum "composer.lock" }}

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - vendor
          key: composer-{{ checksum "composer.lock" }}

      - run:
          name: Build
          command: make build

workflows:
  version: 2
  main:
    jobs:
      - build
